import type { Metadata } from "next"
import "./globals.css"

import Providers from "./Providers"
import UiLayout from "@/components/layout/UiLayout/UiLayout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <UiLayout>
            {children}
          </UiLayout>
        </Providers>
      </body>
    </html>
  )
}